# Generated by Django 6.0 on 2025-12-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=150, verbose_name="Название услуги"),
                ),
                (
                    "short_description",
                    models.CharField(max_length=1000, verbose_name="Название услуги"),
                ),
                (
                    "example",
                    models.CharField(max_length=1000, verbose_name="Пример услуги"),
                ),
                ("full_description", models.TextField(verbose_name="Полное описание")),
                ("price", models.IntegerField(verbose_name="Цена")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/", verbose_name="Фото"
                    ),
                ),
            ],
            options={
                "verbose_name": "услуга",
                "verbose_name_plural": "услуги",
                "ordering": ["title"],
            },
        ),
        migrations.AlterModelOptions(
            name="mainpage",
            options={
                "ordering": ["header_1"],
                "verbose_name": "главная",
                "verbose_name_plural": "главные",
            },
        ),
    ]
