# Generated by Django 6.0 on 2025-12-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_service_alter_mainpage_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="short_description",
            field=models.CharField(max_length=1000, verbose_name="Краткое описание"),
        ),
    ]
