# Generated by Django 6.0 on 2025-12-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_alter_service_short_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="ФИО")),
                (
                    "specialization",
                    models.CharField(max_length=150, verbose_name="Специализация"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/", verbose_name="Фото"
                    ),
                ),
            ],
            options={
                "verbose_name": "врач",
                "verbose_name_plural": "врачи",
                "ordering": ["name"],
            },
        ),
    ]
